default_platform(:android)

platform :android do
  lane :beta do
    gradle(
      task: "assembleDebug"
    )
    apk = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]

      UI.user_error!("APK not found!") if apk.nil?

      tag = ENV["GITHUB_REF_NAME"] || "local"
      new_apk = apk.sub("app-debug.apk", "news-#{tag}.apk")

      sh("mv '#{apk}' '#{new_apk}'")

      firebase_app_distribution(
        app: ENV["FIREBASE_APP_ID"],
        testers: "naimishgupta983842377@gmail.com",
        apk_path: new_apk
      )
  end
end