name: Test Workflow
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Print Commit Info
      - run: |
          echo "Workflow Triggered"
          echo "Commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"
