name: Android CI
on:
  push:
    branches:
      - T0-Base

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: action/checkout@v4

      - uses: actions/setup-java@4
        with:
          distribution: temurin
          java-version: 17


      -run: chmod +x gradlew

      -name: Build App
        run: ./gradlew assembleDebug